/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computersupportapplication;

/**
 *
 * @author John Mc Dermott
 */
public class ComputerSupportGUI extends javax.swing.JFrame {

    /**
     * Creates new form ComputerSupportGUI
     */
    public ComputerSupportGUI()  {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ComputingSupportLbl = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        FAQBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ErrorBankBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BackGroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComputingSupportLbl.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ComputingSupportLbl.setForeground(new java.awt.Color(51, 51, 51));
        ComputingSupportLbl.setText("Computing Support");
        ComputingSupportLbl.setBounds(40, 50, 320, 90);
        jLayeredPane1.add(ComputingSupportLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Mc Dermott\\Documents\\College\\NetBeansProjects\\Project\\ContactUsButton.fw.png")); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(70, 410, 260, 80);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        FAQBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Mc Dermott\\Documents\\College\\NetBeansProjects\\Project\\FAQButton.fw.png")); // NOI18N
        FAQBtn.setText("jButton3");
        FAQBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FAQBtn.setBounds(70, 230, 260, 80);
        jLayeredPane1.add(FAQBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Mc Dermott\\Documents\\College\\NetBeansProjects\\Project\\TimetableButton.fw.png")); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setBounds(70, 320, 260, 80);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ErrorBankBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Mc Dermott\\Documents\\College\\NetBeansProjects\\Project\\ErrorBankButton.fw.png")); // NOI18N
        ErrorBankBtn.setText("jButton5");
        ErrorBankBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ErrorBankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorBankBtnActionPerformed(evt);
            }
        });
        ErrorBankBtn.setBounds(70, 140, 260, 80);
        jLayeredPane1.add(ErrorBankBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Mc Dermott\\Documents\\College\\NetBeansProjects\\Project\\HomeButtonLbl.fw.png")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setBounds(10, 10, 50, 50);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackGroundLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Mc Dermott\\Documents\\College\\NetBeansProjects\\Project\\silver-background.jpg")); // NOI18N
        BackGroundLbl.setBounds(-10, 0, 410, 540);
        jLayeredPane1.add(BackGroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErrorBankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorBankBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorBankBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerSupportGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLbl;
    private javax.swing.JLabel ComputingSupportLbl;
    private javax.swing.JButton ErrorBankBtn;
    private javax.swing.JButton FAQBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
