/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class ComSupErrorBank extends javax.swing.JFrame {

    /**
     * Creates new form ComSupErrorBank
     */
    public ComSupErrorBank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        TitleLbl = new javax.swing.JLabel();
        ErrorEntryTextFld = new javax.swing.JTextField();
        AddErrorBtn = new javax.swing.JButton();
        PleaseEnterSolutionBtn = new javax.swing.JTextField();
        SolutionTextField = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        AddSolutionBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ErrorTextField = new javax.swing.JTextArea();
        SilverBackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\HomeButtonLbl.fw.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(10, 10, 50, 50);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TitleLbl.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(51, 51, 51));
        TitleLbl.setText("Error Bank");
        TitleLbl.setBounds(100, 40, 250, 70);
        jLayeredPane1.add(TitleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ErrorEntryTextFld.setText("Enter your error here");
        ErrorEntryTextFld.setBounds(20, 110, 360, 20);
        jLayeredPane1.add(ErrorEntryTextFld, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AddErrorBtn.setText("Add Error");
        AddErrorBtn.setBounds(280, 140, 100, 23);
        jLayeredPane1.add(AddErrorBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PleaseEnterSolutionBtn.setText("Please enter the erros number followed by your suggested solution here");
        PleaseEnterSolutionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PleaseEnterSolutionBtnActionPerformed(evt);
            }
        });
        PleaseEnterSolutionBtn.setBounds(20, 310, 360, 20);
        jLayeredPane1.add(PleaseEnterSolutionBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        SolutionTextField.setViewportView(jTextArea2);

        SolutionTextField.setBounds(20, 370, 360, 96);
        jLayeredPane1.add(SolutionTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AddSolutionBtn.setText("Add Solution");
        AddSolutionBtn.setBounds(280, 340, 100, 23);
        jLayeredPane1.add(AddSolutionBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ErrorTextField.setColumns(20);
        ErrorTextField.setRows(5);
        ErrorTextField.setText("Previously submitted errors - \n1\n2\n3\n4\n5\netc.\n");
        jScrollPane1.setViewportView(ErrorTextField);

        jScrollPane1.setBounds(20, 170, 360, 130);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SilverBackgroundLbl.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\silver-background.jpg")); // NOI18N
        SilverBackgroundLbl.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(SilverBackgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PleaseEnterSolutionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PleaseEnterSolutionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PleaseEnterSolutionBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComSupErrorBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComSupErrorBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComSupErrorBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComSupErrorBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ComSupErrorBank().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddErrorBtn;
    private javax.swing.JButton AddSolutionBtn;
    private javax.swing.JTextField ErrorEntryTextFld;
    private javax.swing.JTextArea ErrorTextField;
    private javax.swing.JTextField PleaseEnterSolutionBtn;
    private javax.swing.JLabel SilverBackgroundLbl;
    private javax.swing.JScrollPane SolutionTextField;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
