/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class ComSupPage extends javax.swing.JFrame {

    /**
     * Creates new form ComSupPage
     */
    public ComSupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundLayeredPane = new javax.swing.JLayeredPane();
        HomeButtonBtn = new javax.swing.JButton();
        TitleLbl = new javax.swing.JLabel();
        ContactUsBtn = new javax.swing.JButton();
        TimeTableButtonBtn = new javax.swing.JButton();
        ErrorBankBtn = new javax.swing.JButton();
        FAQButtonBtn = new javax.swing.JButton();
        SilverBackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomeButtonBtn.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\HomeButtonLbl.fw.png")); // NOI18N
        HomeButtonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonBtnActionPerformed(evt);
            }
        });
        HomeButtonBtn.setBounds(10, 10, 50, 50);
        BackgroundLayeredPane.add(HomeButtonBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TitleLbl.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(51, 51, 51));
        TitleLbl.setText("Computing Support");
        TitleLbl.setBounds(40, 80, 320, 40);
        BackgroundLayeredPane.add(TitleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ContactUsBtn.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\ContactUsButton.fw.png")); // NOI18N
        ContactUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsBtnActionPerformed(evt);
            }
        });
        ContactUsBtn.setBounds(50, 410, 280, 80);
        BackgroundLayeredPane.add(ContactUsBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TimeTableButtonBtn.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\TimetableButton.fw.png")); // NOI18N
        TimeTableButtonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeTableButtonBtnActionPerformed(evt);
            }
        });
        TimeTableButtonBtn.setBounds(50, 320, 280, 80);
        BackgroundLayeredPane.add(TimeTableButtonBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ErrorBankBtn.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\ErrorBankButton.fw.png")); // NOI18N
        ErrorBankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorBankBtnActionPerformed(evt);
            }
        });
        ErrorBankBtn.setBounds(50, 140, 280, 80);
        BackgroundLayeredPane.add(ErrorBankBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        FAQButtonBtn.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\FAQButton.fw.png")); // NOI18N
        FAQButtonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAQButtonBtnActionPerformed(evt);
            }
        });
        FAQButtonBtn.setBounds(50, 230, 280, 80);
        BackgroundLayeredPane.add(FAQButtonBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SilverBackgroundLbl.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\silver-background.jpg")); // NOI18N
        SilverBackgroundLbl.setBounds(0, 0, 400, 500);
        BackgroundLayeredPane.add(SilverBackgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErrorBankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorBankBtnActionPerformed

        ComSupErrorBank myComSupErrorBank = new ComSupErrorBank();
        myComSupErrorBank.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ErrorBankBtnActionPerformed

    private void FAQButtonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAQButtonBtnActionPerformed
        ComSupFAQ myComSupFAQ = new ComSupFAQ();
        myComSupFAQ.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FAQButtonBtnActionPerformed

    private void TimeTableButtonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeTableButtonBtnActionPerformed
        ComSupTimeTable myComSupTimeTable = new ComSupTimeTable();
        myComSupTimeTable.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TimeTableButtonBtnActionPerformed

    private void ContactUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsBtnActionPerformed
       ComSupContactUs myComSupContactUs = new ComSupContactUs();
        myComSupContactUs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ContactUsBtnActionPerformed

    private void HomeButtonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonBtnActionPerformed
       MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeButtonBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ComSupPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BackgroundLayeredPane;
    private javax.swing.JButton ContactUsBtn;
    private javax.swing.JButton ErrorBankBtn;
    private javax.swing.JButton FAQButtonBtn;
    private javax.swing.JButton HomeButtonBtn;
    private javax.swing.JLabel SilverBackgroundLbl;
    private javax.swing.JButton TimeTableButtonBtn;
    private javax.swing.JLabel TitleLbl;
    // End of variables declaration//GEN-END:variables
}
