/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class ContactPage extends javax.swing.JFrame {

    /**
     * Creates new form ContactPage
     */
    public ContactPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        imgMicLB = new javax.swing.JLabel();
        imgCatLB = new javax.swing.JLabel();
        name1LB = new javax.swing.JLabel();
        role1LB = new javax.swing.JLabel();
        role1pt2LB = new javax.swing.JLabel();
        phone1LB = new javax.swing.JLabel();
        email1LB = new javax.swing.JLabel();
        name2LB = new javax.swing.JLabel();
        role2LB = new javax.swing.JLabel();
        phone2LB = new javax.swing.JLabel();
        email2LB = new javax.swing.JLabel();
        homeBTN = new javax.swing.JButton();
        naviBarLB = new javax.swing.JLabel();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText("Need to get in touch?");
        headerLB.setBounds(70, 10, 260, 50);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imgMicLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\dr-michael-goldrick.jpg")); // NOI18N
        imgMicLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        imgMicLB.setBounds(30, 90, 100, 106);
        jLayeredPane1.add(imgMicLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imgCatLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\catherine-elliott.jpg")); // NOI18N
        imgCatLB.setText("jLabel1");
        imgCatLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        imgCatLB.setBounds(30, 240, 100, 100);
        jLayeredPane1.add(imgCatLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        name1LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        name1LB.setForeground(new java.awt.Color(255, 255, 255));
        name1LB.setText("Name: Dr Micheal Goldrich");
        name1LB.setBounds(150, 90, 180, 15);
        jLayeredPane1.add(name1LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        role1LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        role1LB.setForeground(new java.awt.Color(255, 255, 255));
        role1LB.setText("Role: Learning Support and Development");
        role1LB.setBounds(150, 110, 250, 15);
        jLayeredPane1.add(role1LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        role1pt2LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        role1pt2LB.setForeground(new java.awt.Color(255, 255, 255));
        role1pt2LB.setText(" officer");
        role1pt2LB.setBounds(180, 130, 40, 14);
        jLayeredPane1.add(role1pt2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        phone1LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phone1LB.setForeground(new java.awt.Color(255, 255, 255));
        phone1LB.setText("Phone: 01 6599245");
        phone1LB.setBounds(150, 150, 200, 15);
        jLayeredPane1.add(phone1LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        email1LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email1LB.setForeground(new java.awt.Color(255, 255, 255));
        email1LB.setText("Email: michael.goldrick@ncirl.ie");
        email1LB.setBounds(150, 170, 210, 15);
        jLayeredPane1.add(email1LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        name2LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        name2LB.setForeground(new java.awt.Color(255, 255, 255));
        name2LB.setText("Name: Catherine Elliot  ");
        name2LB.setBounds(150, 240, 180, 15);
        jLayeredPane1.add(name2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        role2LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        role2LB.setForeground(new java.awt.Color(255, 255, 255));
        role2LB.setText("Role: Learning Support Tutor");
        role2LB.setBounds(150, 260, 190, 15);
        jLayeredPane1.add(role2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        phone2LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phone2LB.setForeground(new java.awt.Color(255, 255, 255));
        phone2LB.setText("Phone: 01 6599208");
        phone2LB.setBounds(150, 280, 150, 15);
        jLayeredPane1.add(phone2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        email2LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email2LB.setForeground(new java.awt.Color(255, 255, 255));
        email2LB.setText("Email: catherine.elliott@ncirl.ie");
        email2LB.setBounds(150, 300, 169, 15);
        jLayeredPane1.add(email2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\png\\HomeButtonLbl.fw.png")); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(170, 440, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        naviBarLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\navigationBar.jpg")); // NOI18N
        naviBarLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        naviBarLB.setBounds(0, 430, 400, 70);
        jLayeredPane1.add(naviBarLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\App background.jpg")); // NOI18N
        wrapperLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
        MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ContactPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email1LB;
    private javax.swing.JLabel email2LB;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLabel imgCatLB;
    private javax.swing.JLabel imgMicLB;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel name1LB;
    private javax.swing.JLabel name2LB;
    private javax.swing.JLabel naviBarLB;
    private javax.swing.JLabel phone1LB;
    private javax.swing.JLabel phone2LB;
    private javax.swing.JLabel role1LB;
    private javax.swing.JLabel role1pt2LB;
    private javax.swing.JLabel role2LB;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
