/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class DisAPPpage extends javax.swing.JFrame {

    /**
     * Creates new form DisAPPpage
     */
    public DisAPPpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        DisAPPTitleLabel = new javax.swing.JLabel();
        HomeMapBtn = new javax.swing.JButton();
        DisAppFAQBtn = new javax.swing.JButton();
        DisAppActBtn = new javax.swing.JButton();
        DisAppContactBtn = new javax.swing.JButton();
        DisAppServicesBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        DisAppHomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisAPPTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        DisAPPTitleLabel.setForeground(new java.awt.Color(153, 0, 0));
        DisAPPTitleLabel.setText("Disability Application");
        DisAPPTitleLabel.setBounds(10, 0, 390, 50);
        jLayeredPane1.add(DisAPPTitleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        HomeMapBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        HomeMapBtn.setText("Map");
        HomeMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMapBtnActionPerformed(evt);
            }
        });
        HomeMapBtn.setBounds(10, 90, 130, 70);
        jLayeredPane1.add(HomeMapBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DisAppFAQBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        DisAppFAQBtn.setText("FAQ");
        DisAppFAQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisAppFAQBtnActionPerformed(evt);
            }
        });
        DisAppFAQBtn.setBounds(240, 90, 140, 70);
        jLayeredPane1.add(DisAppFAQBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DisAppActBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        DisAppActBtn.setText("Disability Act");
        DisAppActBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisAppActBtnActionPerformed(evt);
            }
        });
        DisAppActBtn.setBounds(120, 190, 130, 80);
        jLayeredPane1.add(DisAppActBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DisAppContactBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        DisAppContactBtn.setText("Contact");
        DisAppContactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisAppContactBtnActionPerformed(evt);
            }
        });
        DisAppContactBtn.setBounds(10, 320, 130, 70);
        jLayeredPane1.add(DisAppContactBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DisAppServicesBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        DisAppServicesBtn.setText("Services");
        DisAppServicesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisAppServicesBtnActionPerformed(evt);
            }
        });
        DisAppServicesBtn.setBounds(240, 320, 140, 70);
        jLayeredPane1.add(DisAppServicesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\SENDTODAVE\\HomeButtonLbl.fw.png")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(170, 430, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DisAppHomeLabel.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Background.jpg")); // NOI18N
        DisAppHomeLabel.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(DisAppHomeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMapBtnActionPerformed
        DisAPPMap myMap = new DisAPPMap();
        myMap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMapBtnActionPerformed

    private void DisAppFAQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisAppFAQBtnActionPerformed
        DisAppFAQ myFAQ = new DisAppFAQ();
        myFAQ.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DisAppFAQBtnActionPerformed

    private void DisAppActBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisAppActBtnActionPerformed
        DisabilityAct myDisAct = new DisabilityAct();
        myDisAct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DisAppActBtnActionPerformed

    private void DisAppContactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisAppContactBtnActionPerformed
      Contacts myCont = new Contacts();
       myCont.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_DisAppContactBtnActionPerformed

    private void DisAppServicesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisAppServicesBtnActionPerformed

        DisabilityServices myDisabilityServices = new DisabilityServices();
        myDisabilityServices.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DisAppServicesBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisAPPpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisAPPpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisAPPpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisAPPpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DisAPPpage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisAPPTitleLabel;
    private javax.swing.JButton DisAppActBtn;
    private javax.swing.JButton DisAppContactBtn;
    private javax.swing.JButton DisAppFAQBtn;
    private javax.swing.JLabel DisAppHomeLabel;
    private javax.swing.JButton DisAppServicesBtn;
    private javax.swing.JButton HomeMapBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
