/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class FAQ extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public FAQ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        homeBTN = new javax.swing.JButton();
        naviBarLB = new javax.swing.JLabel();
        q1BT = new javax.swing.JButton();
        q3BT = new javax.swing.JButton();
        q4BT = new javax.swing.JButton();
        q2BT = new javax.swing.JButton();
        q5BT = new javax.swing.JButton();
        q6BT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textBoxTA = new javax.swing.JTextArea();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText("FAQ's");
        headerLB.setBounds(160, 20, 70, 30);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\png\\HomeButtonLbl.fw.png")); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(170, 430, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        naviBarLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\navigationBar.jpg")); // NOI18N
        naviBarLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        naviBarLB.setBounds(0, 410, 400, 90);
        jLayeredPane1.add(naviBarLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q1BT.setText("Question 1 : ");
        buttonGroup1.add(q1BT);
        q1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1BTActionPerformed(evt);
            }
        });
        q1BT.setBounds(30, 70, 340, 23);
        jLayeredPane1.add(q1BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q3BT.setText("Question 3 : ");
        buttonGroup1.add(q3BT);
        q3BT.setBounds(30, 130, 340, 23);
        jLayeredPane1.add(q3BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q4BT.setText("Question 4 : ");
        buttonGroup1.add(q4BT);
        q4BT.setBounds(30, 160, 340, 23);
        jLayeredPane1.add(q4BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q2BT.setText("Question 2 : ");
        buttonGroup1.add(q2BT);
        q2BT.setBounds(30, 100, 340, 23);
        jLayeredPane1.add(q2BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q5BT.setText("Question 5 : ");
        buttonGroup1.add(q5BT);
        q5BT.setBounds(30, 190, 340, 23);
        jLayeredPane1.add(q5BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q6BT.setText("Question 6 : ");
        buttonGroup1.add(q6BT);
        q6BT.setBounds(30, 220, 340, 23);
        jLayeredPane1.add(q6BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        textBoxTA.setBackground(new java.awt.Color(102, 102, 102));
        textBoxTA.setColumns(20);
        textBoxTA.setForeground(new java.awt.Color(255, 255, 255));
        textBoxTA.setRows(5);
        jScrollPane2.setViewportView(textBoxTA);

        jScrollPane2.setBounds(20, 260, 360, 140);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\App background.jpg")); // NOI18N
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1BTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1BTActionPerformed

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
       MainPage myMainPage = new MainPage();
       myMainPage.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FAQ().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel naviBarLB;
    private javax.swing.JButton q1BT;
    private javax.swing.JButton q2BT;
    private javax.swing.JButton q3BT;
    private javax.swing.JButton q4BT;
    private javax.swing.JButton q5BT;
    private javax.swing.JButton q6BT;
    private javax.swing.JTextArea textBoxTA;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
