/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class LearnSupPage extends javax.swing.JFrame {

    /**
     * Creates new form LearnSupPage
     */
    public LearnSupPage() {
        initComponents();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBTN = new javax.swing.JButton();
        faqBTN = new javax.swing.JButton();
        contactBTN = new javax.swing.JButton();
        servicesBTN = new javax.swing.JButton();
        appointmentsBTN = new javax.swing.JButton();
        timerBTN = new javax.swing.JButton();
        headerLB = new javax.swing.JLabel();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\Home1BTN.jpg")); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(80, 340, 100, 100);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        faqBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\FAQBTN.jpg")); // NOI18N
        faqBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faqBTNActionPerformed(evt);
            }
        });
        faqBTN.setBounds(220, 100, 100, 100);
        jLayeredPane1.add(faqBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        contactBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\ContactBTN.jpg")); // NOI18N
        contactBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBTNActionPerformed(evt);
            }
        });
        contactBTN.setBounds(80, 220, 100, 100);
        jLayeredPane1.add(contactBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        servicesBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\ServicesBTN.jpg")); // NOI18N
        servicesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesBTNActionPerformed(evt);
            }
        });
        servicesBTN.setBounds(80, 100, 100, 100);
        jLayeredPane1.add(servicesBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        appointmentsBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\Jpeg\\appointmentsBTN.jpg")); // NOI18N
        appointmentsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsBTNActionPerformed(evt);
            }
        });
        appointmentsBTN.setBounds(220, 220, 100, 100);
        jLayeredPane1.add(appointmentsBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        timerBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\TimerBTN.jpg")); // NOI18N
        timerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerBTNActionPerformed(evt);
            }
        });
        timerBTN.setBounds(220, 340, 100, 100);
        jLayeredPane1.add(timerBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText(" Learning Support");
        headerLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        headerLB.setBounds(90, 10, 220, 60);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\App background.jpg")); // NOI18N
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
       MainPage myMainPage = new MainPage();
       myMainPage.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    private void timerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerBTNActionPerformed
       SubTimer myTimer = new SubTimer();
       myTimer.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_timerBTNActionPerformed

    private void contactBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBTNActionPerformed
        ContactPage myContact = new ContactPage();
        myContact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactBTNActionPerformed

    private void faqBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faqBTNActionPerformed
        FAQ myFaq = new FAQ();
        myFaq.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_faqBTNActionPerformed

    private void appointmentsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsBTNActionPerformed
        Appointments myAppointment = new Appointments();
        myAppointment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_appointmentsBTNActionPerformed

    private void servicesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesBTNActionPerformed
        Services myServices = new Services();
        myServices.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_servicesBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnSupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LearnSupPage().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentsBTN;
    private javax.swing.JButton contactBTN;
    private javax.swing.JButton faqBTN;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton servicesBTN;
    private javax.swing.JButton timerBTN;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
