/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        learnSupBT = new javax.swing.JButton();
        compSupBT = new javax.swing.JButton();
        disaSupBT = new javax.swing.JButton();
        borderLB = new javax.swing.JLabel();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\MainInterface\\jpeg\\Header.jpg")); // NOI18N
        headerLB.setBounds(20, 30, 350, 50);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learnSupBT.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\DAVESBUTTON.fw.jpg")); // NOI18N
        learnSupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnSupBTActionPerformed(evt);
            }
        });
        learnSupBT.setBounds(70, 270, 260, 60);
        jLayeredPane1.add(learnSupBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        compSupBT.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\ComputerSupportApp\\Jpeg\\JOHNSBUTTON.fw.jpg")); // NOI18N
        compSupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compSupBTActionPerformed(evt);
            }
        });
        compSupBT.setBounds(70, 340, 260, 60);
        jLayeredPane1.add(compSupBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disaSupBT.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\DisabilitySupportApp\\JPEG\\REILLYSBUTTON.fw.jpg")); // NOI18N
        disaSupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disaSupBTActionPerformed(evt);
            }
        });
        disaSupBT.setBounds(70, 410, 260, 60);
        jLayeredPane1.add(disaSupBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        borderLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        borderLB.setBounds(60, 260, 280, 220);
        jLayeredPane1.add(borderLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\MainInterface\\jpeg\\MainInterfaceBackground.jpg")); // NOI18N
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learnSupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnSupBTActionPerformed
        LearnSupPage myLearnSupPage = new LearnSupPage();
        myLearnSupPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_learnSupBTActionPerformed

    private void disaSupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disaSupBTActionPerformed
       DisAPPpage myDisApp = new DisAPPpage();
       myDisApp.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_disaSupBTActionPerformed

    private void compSupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compSupBTActionPerformed
        ComSupPage myComSupPage = new ComSupPage();
        myComSupPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_compSupBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borderLB;
    private javax.swing.JButton compSupBT;
    private javax.swing.JButton disaSupBT;
    private javax.swing.JLabel headerLB;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton learnSupBT;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
