/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class Services extends javax.swing.JFrame {

    /**
     * Creates new form Services
     */
    public Services() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        manualBTN = new javax.swing.JButton();
        mindTrainingBTN = new javax.swing.JButton();
        screeningBTN = new javax.swing.JButton();
        harvardBTN = new javax.swing.JButton();
        virtualBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTA = new javax.swing.JTextArea();
        homeBTN = new javax.swing.JButton();
        naviBarLB = new javax.swing.JLabel();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText("Services");
        headerLB.setBounds(150, 20, 100, 29);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        manualBTN.setText("Learning Development Manual");
        manualBTN.setBounds(40, 70, 320, 30);
        jLayeredPane1.add(manualBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mindTrainingBTN.setText("Mind Training");
        mindTrainingBTN.setBounds(40, 110, 320, 30);
        jLayeredPane1.add(mindTrainingBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        screeningBTN.setText("Dyslexia Screening");
        screeningBTN.setBounds(40, 150, 320, 30);
        jLayeredPane1.add(screeningBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        harvardBTN.setText("Harvard Learning Style");
        harvardBTN.setBounds(40, 190, 320, 30);
        jLayeredPane1.add(harvardBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        virtualBTN.setText("Virtual Learning Center");
        virtualBTN.setBounds(40, 230, 320, 30);
        jLayeredPane1.add(virtualBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textTA.setBackground(new java.awt.Color(51, 51, 51));
        textTA.setColumns(20);
        textTA.setForeground(new java.awt.Color(255, 255, 255));
        textTA.setRows(5);
        jScrollPane1.setViewportView(textTA);

        jScrollPane1.setBounds(40, 270, 320, 140);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\png\\HomeButtonLbl.fw.png")); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(170, 440, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        naviBarLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\navigationBar.jpg")); // NOI18N
        naviBarLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        naviBarLB.setBounds(0, 420, 400, 80);
        jLayeredPane1.add(naviBarLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\App background.jpg")); // NOI18N
        wrapperLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
        MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Services().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton harvardBTN;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manualBTN;
    private javax.swing.JButton mindTrainingBTN;
    private javax.swing.JLabel naviBarLB;
    private javax.swing.JButton screeningBTN;
    private javax.swing.JTextArea textTA;
    private javax.swing.JButton virtualBTN;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
