/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 */
public class SubTimer extends javax.swing.JFrame {

    /**
     * Creates new form SubTimer
     */
    public SubTimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        prompt1LB = new javax.swing.JLabel();
        monthLB = new javax.swing.JLabel();
        dayLb = new javax.swing.JLabel();
        hourLB = new javax.swing.JLabel();
        minLB = new javax.swing.JLabel();
        monthTF = new javax.swing.JTextField();
        dayTF = new javax.swing.JTextField();
        hourTF = new javax.swing.JTextField();
        minTF = new javax.swing.JTextField();
        prompt2LB = new javax.swing.JLabel();
        time1LB = new javax.swing.JLabel();
        prompt3LB = new javax.swing.JLabel();
        time2LB = new javax.swing.JLabel();
        homeBTN = new javax.swing.JButton();
        naviBarLB = new javax.swing.JLabel();
        wrapperLB = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText("Submission Deadline Timer");
        headerLB.setBounds(40, 20, 320, 29);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prompt1LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prompt1LB.setForeground(new java.awt.Color(255, 255, 255));
        prompt1LB.setText("Please enter the date and time of your submission dadline: ");
        prompt1LB.setBounds(20, 70, 330, 15);
        jLayeredPane1.add(prompt1LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        monthLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        monthLB.setForeground(new java.awt.Color(255, 255, 255));
        monthLB.setText("Month");
        monthLB.setBounds(40, 120, 45, 17);
        jLayeredPane1.add(monthLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dayLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dayLb.setForeground(new java.awt.Color(255, 255, 255));
        dayLb.setText("Day");
        dayLb.setBounds(140, 120, 25, 17);
        jLayeredPane1.add(dayLb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hourLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        hourLB.setForeground(new java.awt.Color(255, 255, 255));
        hourLB.setText("Hour");
        hourLB.setBounds(230, 120, 34, 17);
        jLayeredPane1.add(hourLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        minLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minLB.setForeground(new java.awt.Color(255, 255, 255));
        minLB.setText("Minute");
        minLB.setBounds(310, 120, 50, 17);
        jLayeredPane1.add(minLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        monthTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        monthTF.setBounds(40, 140, 50, 30);
        jLayeredPane1.add(monthTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dayTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dayTF.setBounds(130, 140, 50, 30);
        jLayeredPane1.add(dayTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hourTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        hourTF.setBounds(220, 140, 50, 30);
        jLayeredPane1.add(hourTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        minTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minTF.setBounds(310, 140, 50, 30);
        jLayeredPane1.add(minTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prompt2LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prompt2LB.setForeground(new java.awt.Color(255, 255, 255));
        prompt2LB.setText("Time remaining until submission is due: ");
        prompt2LB.setBounds(20, 210, 270, 15);
        jLayeredPane1.add(prompt2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        time1LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        time1LB.setForeground(new java.awt.Color(255, 255, 255));
        time1LB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        time1LB.setBounds(20, 240, 350, 50);
        jLayeredPane1.add(time1LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prompt3LB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prompt3LB.setForeground(new java.awt.Color(255, 255, 255));
        prompt3LB.setText("If you wish to avail of proof reading services, submit by: ");
        prompt3LB.setBounds(20, 310, 340, 15);
        jLayeredPane1.add(prompt3LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        time2LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        time2LB.setForeground(new java.awt.Color(255, 255, 255));
        time2LB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        time2LB.setBounds(20, 340, 350, 50);
        jLayeredPane1.add(time2LB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBTN.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\png\\HomeButtonLbl.fw.png")); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(170, 430, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        naviBarLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\navigationBar.jpg")); // NOI18N
        naviBarLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        naviBarLB.setBounds(0, 410, 400, 90);
        jLayeredPane1.add(naviBarLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon("H:\\Semester 2\\Object Orientated Programming\\Team C OOP Project\\Images\\LearningSupportApp\\jpeg\\App background.jpg")); // NOI18N
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
        MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SubTimer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayLb;
    private javax.swing.JTextField dayTF;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLabel hourLB;
    private javax.swing.JTextField hourTF;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel minLB;
    private javax.swing.JTextField minTF;
    private javax.swing.JLabel monthLB;
    private javax.swing.JTextField monthTF;
    private javax.swing.JLabel naviBarLB;
    private javax.swing.JLabel prompt1LB;
    private javax.swing.JLabel prompt2LB;
    private javax.swing.JLabel prompt3LB;
    private javax.swing.JLabel time1LB;
    private javax.swing.JLabel time2LB;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
